global:
  scrape_interval: 5s 
  evaluation_interval: 5s 
  
rule_files:

scrape_configs:
  
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "fastapi"
    static_configs:
      - targets: ["127.0.0.0:8000"]